### ISSUE TITLE
Community participation roles

### ISSUE THREAD

**Issue by Rumyra** [mdn/project-template#8]
- [x] 'Roles' & 'stepping down' should be same level
- [x] Community participant and contributor squash into one
- [x] Roles -> Levels at top community member/contributor, spotlight contributor, maintainer, owner
- [ ] Specialised roles -> Community manager (make more generic), Invited Experts,
- [ ] Move to MDN (do last after final edit)

**Comment by dipikabh** [comment]
Existing page on MDN: https://developer.mozilla.org/en-US/docs/MDN/Community/Users_teams
